# Tested with Ansible 2.10.7

---
- name: Delete BIG-IP VE VM on Microsoft Azure
  hosts: localhost
  vars_files:
  - "../inventory/group_vars/azure.yml"
  gather_facts: no
  connection: local
  collections: 
  - azure.azcollection.azure_rm_virtualmachine

  tasks:

    - name: Delete a BIG-IP VE VM and all resources that were autocreated
      azure_rm_virtualmachine:
        resource_group: "{{ az_rg }}"
        location: "{{ az_region }}"
        name: "{{ hostname }}"
        state: absent
        remove_on_absent: all_autocreated
...