---
az_region: "japaneast"
az_rg: "Azure_sample"
admin_user: "admin"
admin_password: "xxxxx"
hostname: "test01"
instance_type: "Standard_DS3_v2"
#instance_type: "Standard_A3"
#instance_type: "Standard_A4"
#instance_type: "Standard_A5"
#instance_type: "Standard_A6"
#instance_type: "Standard_A7"
#instance_type: "Standard_D3"
#instance_type: "Standard_D4"
#instance_type: "Standard_D11"
#instance_type: "Standard_D12"
#instance_type: "Standard_D13"
#instance_type: "Standard_D14"
#instance_type: "Standard_DS3"
#instance_type: "Standard_DS4"
#instance_type: "Standard_DS11"
#instance_type: "Standard_DS12"
#instance_type: "Standard_DS13"
#instance_type: "Standard_DS14"
#instance_type: "Standard_D3_v2"
#instance_type: "Standard_D4_v2"
#instance_type: "Standard_D5_v2"
#instance_type: "Standard_D11_v2"
#instance_type: "Standard_D12_v2"
#instance_type: "Standard_D13_v2"
#instance_type: "Standard_D14_v2"
#instance_type: "Standard_D15_v2"
#instance_type: "Standard_DS3_v2"
#instance_type: "Standard_DS4_v2"
#instance_type: "Standard_DS5_v2"
#instance_type: "Standard_DS11_v2"
#instance_type: "Standard_DS12_v2"
#instance_type: "Standard_DS13_v2"
#instance_type: "Standard_DS14_v2"
#instance_type: "Standard_DS15_v2"
#instance_type: "Standard_F4"
#instance_type: "Standard_F8"
#instance_type: "Standard_F4S"
#instance_type: "Standard_F8S"
#instance_type: "Standard_F16S"
#instance_type: "Standard_G3"
#instance_type: "Standard_G4"
#instance_type: "Standard_G5"
#instance_type: "Standard_GS3"
#instance_type: "Standard_GS4"
#instance_type: "Standard_GS5"
bigip_image: "LTMOneBootLocation"
#bigip_image: "LTMTwoBootLocations"
#bigip_image: "AllOneBootLocation"
#bigip_image: "AllTwoBootLocations"
bigip_version: "15.1.201000"
resource_provisioning: "ltm:nominal"
#resource_provisioning: "ltm:nominal,asm:nominal"
reg_key: "XXXXX-XXXXX-XXXXX-XXXXX-XXXXXXX"
az_vnet: "Azure_vnet_sample"
az_mgmtsubnet: "subnet-mgmt"
az_extsubnet: "subnet-external"
az_intsubnet: "subnet-internal"
ntpserver: "ntp.nict.jp"
timezone: "Asia/Tokyo"
...